/** @type {import('tailwindcss').Config} */
const colorToken = (token) => `rgb(var(${token}) / <alpha-value>)`;

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'background': colorToken('--color-background'),
        'error': colorToken('--color-error'),
        'error-container': colorToken('--color-error-container'),
        'inverse-on-surface': colorToken('--color-inverse-on-surface'),
        'inverse-primary': colorToken('--color-inverse-primary'),
        'inverse-surface': colorToken('--color-inverse-surface'),
        'on-background': colorToken('--color-on-background'),
        'on-error': colorToken('--color-on-error'),
        'on-error-container': colorToken('--color-on-error-container'),
        'on-primary': colorToken('--color-on-primary'),
        'on-primary-container': colorToken('--color-on-primary-container'),
        'on-primary-fixed': colorToken('--color-on-primary-fixed'),
        'on-primary-fixed-variant': colorToken('--color-on-primary-fixed-variant'),
        'on-secondary': colorToken('--color-on-secondary'),
        'on-secondary-container': colorToken('--color-on-secondary-container'),
        'on-secondary-fixed': colorToken('--color-on-secondary-fixed'),
        'on-secondary-fixed-variant': colorToken('--color-on-secondary-fixed-variant'),
        'on-surface': colorToken('--color-on-surface'),
        'on-surface-variant': colorToken('--color-on-surface-variant'),
        'on-tertiary': colorToken('--color-on-tertiary'),
        'on-tertiary-container': colorToken('--color-on-tertiary-container'),
        'on-tertiary-fixed': colorToken('--color-on-tertiary-fixed'),
        'on-tertiary-fixed-variant': colorToken('--color-on-tertiary-fixed-variant'),
        'outline': colorToken('--color-outline'),
        'outline-variant': colorToken('--color-outline-variant'),
        'primary': colorToken('--color-primary'),
        'primary-container': colorToken('--color-primary-container'),
        'primary-fixed': colorToken('--color-primary-fixed'),
        'primary-fixed-dim': colorToken('--color-primary-fixed-dim'),
        'secondary': colorToken('--color-secondary'),
        'secondary-container': colorToken('--color-secondary-container'),
        'secondary-fixed': colorToken('--color-secondary-fixed'),
        'secondary-fixed-dim': colorToken('--color-secondary-fixed-dim'),
        'surface': colorToken('--color-surface'),
        'surface-bright': colorToken('--color-surface-bright'),
        'surface-container': colorToken('--color-surface-container'),
        'surface-container-high': colorToken('--color-surface-container-high'),
        'surface-container-highest': colorToken('--color-surface-container-highest'),
        'surface-container-low': colorToken('--color-surface-container-low'),
        'surface-container-lowest': colorToken('--color-surface-container-lowest'),
        'surface-dim': colorToken('--color-surface-dim'),
        'surface-tint': colorToken('--color-surface-tint'),
        'surface-variant': colorToken('--color-surface-variant'),
        'tertiary': colorToken('--color-tertiary'),
        'tertiary-container': colorToken('--color-tertiary-container'),
        'tertiary-fixed': colorToken('--color-tertiary-fixed'),
        'tertiary-fixed-dim': colorToken('--color-tertiary-fixed-dim'),
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        full: '9999px',
        lg: '1rem',
        xl: '1.5rem',
      },
    },
  },
  plugins: [],
};
